### ISSUE TITLE
~

### ISSUE THREAD

**Issue by FahShaTzy** [Alex21321312/devilgama-technology#1]
Nav e pas scroll naik dibuat translateY(0) ben apik jal

**Comment by Alex21321312** [comment]
Ok ok makasih

**Comment by FahShaTzy** [comment]
wkwk, kui maksute nek pas di scroll up njur nav e ra nge blink teko2 muncul, ning digawe transisi koyo pas scroll down :)

**Comment by Alex21321312** [comment]
ok
